version: "3"
services:
  target:
    ports:
      - 9100:8080
    volumes:
      - ${PWD}:/project
    working_dir: /project
    entrypoint: ["/project/init.sh"]
    command: ["/bin/bash"]
    hostname: example
    image: docker.io/node:18.17.0
    depends_on: [neo4j]
  neo4j:
    image: docker.io/neo4j:2025.02.0
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/admin123
